create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
create table account (balance double default 0.00 not null, id bigint not null auto_increment, account_holder_name varchar(100) not null, primary key (id)) engine=InnoDB;
alter table account add constraint idx_account_account_holder_name unique (account_holder_name);
insert into account(account_holder_name, balance) values('adalbertónño-cheking', 1000.00);
insert into account(account_holder_name, balance) values('yilian-cheking', 2000.10);
insert into account(account_holder_name) values('yilian-saving');
